---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world-app
  labels:
    app: nginx-hello-world-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-hello-world-app
  template:
    metadata:
      labels:
        app: nginx-hello-world-app
      
      containers:
      - name: nginx
        image: <AWS_ECR_REGISTRY_ID>.dkr.ecr.us-east-1.amazonaws.com/nginx-hello-world-app:<TAG>
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: nginx-hello-world-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80